// app/admin.js — Rev7.3 FULL (table + dropdowns + daily + PDF)
(function(){
  const $=id=>document.getElementById(id);
  const qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const L=()=> (localStorage.getItem('pm_lang')==='EN'?'EN':'AR');
  let lastName='', renderedLang=L();

  // fixed lists (merged with Excel values)
  const EMP_FIX=['حامد الجابر','ناصر كامل','يوسف محمد','عبد الله الصواف','أحمد عاص','أحمد الحاج','عماد القيسي','خالد عوض','شادي المصري','محمد موسى','علاء إسماعيل','علي الشريف','وسام العساف','محمد مهزع','لؤي جمال'];
  const COND_FIX_AR=['جيد','نشط','خارج الخدمة']; const COND_FIX_EN=['Good','Active','Out of service'];
  const FREQ_FIX_AR=['يومي','أسبوعي','شهري']; const FREQ_FIX_EN=['Daily','Weekly','Monthly'];

  function T(){ return { AR:{hello:'أهلًا', hint:'اعمل على PM MAINTENANCE.xlsx مباشرة (قابل للتعديل). الملف بجانب index.html', back:'رجوع', daily:'ليستة التشييك اليومية (حسب التواريخ والتردد)', gen:'توليد اليوم', dailyPdf:'تصدير PDF', share:'مشاركة', exportPM:'تصدير XLSX', save:'حفظ (ON)', search:'بحث بالكود', shift:'توزيع على الشِّفتات', am:'صباحي', pm:'مسائي', night:'ليلي', total:'الإجمالي اليومي', count:'العدد:'}, EN:{hello:'Welcome', hint:'Edit PM MAINTENANCE.xlsx inline (editable). Place it next to index.html', back:'Back', daily:'Daily PM list (by dates & frequency)', gen:'Generate today', dailyPdf:'Export PDF', share:'Share', exportPM:'Export XLSX', save:'Save (ON)', search:'Search by code', shift:'Split by shifts', am:'Morning', pm:'Evening', night:'Night', total:'Total today', count:'Count:'} }[L()]; }

  function headDisplay(h){ const s=String(h||'').toLowerCase(); const key=s.replace(/\s+/g,' ').trim(); const M={ 'code #':{AR:'كود #',EN:'Code #'}, 'code':{AR:'كود #',EN:'Code #'}, 'machine name':{AR:'اسم الماكينة',EN:'Machine name'}, 'location':{AR:'الموقع',EN:'Location'}, 'p.m frequency':{AR:'تكرار P.M',EN:'P.M Frequency'}, 'pm frequency':{AR:'تكرار P.M',EN:'P.M Frequency'}, 'p.m date':{AR:'تاريخ P.M',EN:'P.M Date'}, 'last service date':{AR:'تاريخ آخر صيانة',EN:'Last Service Date'}, 'condition':{AR:'الحالة',EN:'Condition'}, 'maintenance employee name':{AR:'فني الصيانة',EN:'Maintenance employee name'}, 'status filled by the supervisor':{AR:'حالة (المشرف)',EN:'Status filled by the supervisor'}, 'supervisor name':{AR:'اسم المشرف',EN:'Supervisor name'}, 'supervisor acceptance':{AR:'قبول المشرف',EN:'Supervisor acceptance'}, 'remark':{AR:'ملاحظة',EN:'Remark'}, 'notes':{AR:'ملاحظات',EN:'Notes'}, 'action':{AR:'إجراء',EN:'Action'} }; if(M[key]) return M[key][L()]; if(key.includes('code')) return L()==='AR'?'كود #':'Code #'; if(key.includes('machine')) return L()==='AR'?'اسم الماكينة':'Machine name'; if(key.includes('location')) return L()==='AR'?'الموقع':'Location'; if(key.includes('frequency')) return L()==='AR'?'تكرار P.M':'P.M Frequency'; if(key.includes('condition')) return L()==='AR'?'الحالة':'Condition'; if(key.includes('date')) return L()==='AR'?'تاريخ':'Date'; if(/remark|note|action/.test(key)) return L()==='AR'?'ملاحظات/إجراء':'Remarks/Action'; return h; }

  async function askPinAndOpen(){ try{ let displayName=''; const r=await fetch('./admin/admin.json',{cache:'no-store'}); if(r.ok){ const conf=await r.json(); const pin=prompt(L()==='AR'?'أدخل الرقم السري':'Enter PIN'); if(Array.isArray(conf.users)){ const u=conf.users.find(u=> String(u.pin)===String(pin)); if(!u){ alert(L()==='AR'?'PIN غير صحيح':'Invalid PIN'); return; } displayName=u.name||''; } else if(conf && conf.pin){ if(String(conf.pin)!==String(pin)){ alert(L()==='AR'?'PIN غير صحيح':'Invalid PIN'); return; } displayName=conf.name||''; } } openAdmin(displayName); }catch(_){ openAdmin(''); } }

  async function fetchPMFile(){ const c=['./PM MAINTENANCE.xlsx','./PM%20MAINTENANCE.xlsx','PM MAINTENANCE.xlsx','PM_MAINTENANCE.xlsx']; let last=null; for(const url of c){ try{ const r=await fetch(url,{cache:'no-store'}); if(r.ok){ const ab=await r.arrayBuffer(); return {ab,url}; } last=`HTTP ${r.status}`; }catch(e){ last=(e&&e.message)? e.message: String(e); } } throw new Error(last||'not found'); }

  function ensureDL(id, arr){ let dl=$(id); if(!dl){ dl=document.createElement('datalist'); dl.id=id.slice(1); document.body.appendChild(dl); } const s=new Set(); dl.innerHTML=''; (arr||[]).forEach(v=>{ const t=String(v||'').trim(); if(!t) return; const k=t.toLowerCase(); if(s.has(k)) return; s.add(k); const o=document.createElement('option'); o.value=t; dl.appendChild(o); }); }

  function renderTable(head, low, data, host, lists){ host.innerHTML=''; const wrap=document.createElement('div'); wrap.style.overflow='auto'; wrap.style.maxWidth='100%'; wrap.style.border='1px solid #e8eef6'; wrap.style.borderRadius='10px'; const table=document.createElement('table'); table.style.minWidth='2200px'; const trh=document.createElement('tr'); head.forEach(h=>{ const th=document.createElement('th'); th.textContent=headDisplay(h); th.style.position='sticky'; th.style.top='0'; th.style.background='#f4f9ff'; th.style.padding='12px'; trh.appendChild(th); }); table.appendChild(trh);
    const norm=(s)=> String(s||'').toLowerCase().replace(/\s+/g,' ');
    const roKeys=['code','machine','location','manufacturer','warranty','serial number','purchase date','in date'];

    ensureDL('#dl_cond', (lists.cond||[]).concat(L()==='AR'?COND_FIX_AR:COND_FIX_EN));
    ensureDL('#dl_freq', (lists.freq||[]).concat(L()==='AR'?FREQ_FIX_AR:FREQ_FIX_EN));
    ensureDL('#dl_emp', (lists.emp||[]).concat(EMP_FIX));

    data.forEach(row=>{ const tr=document.createElement('tr'); head.forEach((h,i)=>{ const td=document.createElement('td'); const cap=document.createElement('span'); cap.className='colcap'; cap.textContent=headDisplay(h); td.appendChild(cap);
      let val=row[i]; const hk=norm(h);
      if(/date/.test(hk)){ const n=Number(val); if(isFinite(n) && n>20000 && n<60000){ const base=new Date(Date.UTC(1899,11,30)); const d=new Date(base.getTime()+Math.round(n)*86400000); val=`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`; } }
      const isCode=hk.includes('code'); const isRO=isCode||roKeys.some(k=> hk.includes(k)); let c;
      if(isRO){ c=document.createElement('input'); c.type='text'; c.readOnly=true; c.value=(val==null?'':val); c.style.border='2px solid #e1e7f1'; c.style.fontWeight='700'; }
      else if(hk.includes('condition')){ c=document.createElement('input'); c.setAttribute('list','dl_cond'); c.value=(val==null?'':val); }
      else if((hk.includes('p.m')&&hk.includes('frequency')) || (hk.includes('pm')&&hk.includes('frequency'))){ c=document.createElement('input'); c.setAttribute('list','dl_freq'); c.value=(val==null?'':val); }
      else if(hk.includes('maintenance employee name')){ c=document.createElement('input'); c.setAttribute('list','dl_emp'); c.value=(val==null?'':val); }
      else if(/remark|notes|action|ملاحظ|إجراء/.test(hk)){ c=document.createElement('textarea'); c.rows=3; c.style.minHeight='110px'; c.value=(val==null?'':val); }
      else if(/date/.test(hk)){ c=document.createElement('input'); c.type='date'; c.value=(val==null?'':val); }
      else { c=document.createElement('input'); c.type='text'; c.value=(val==null?'':val); }
      c.style.width='100%'; c.style.maxWidth='100%'; c.style.minWidth='220px'; c.style.fontSize='16px'; c.style.padding='10px'; c.style.color='#0b1324'; c.style.borderRadius='8px'; c.oninput=()=>{ row[i]=c.value; };
      td.appendChild(c);
      if(!isRO){ const del=document.createElement('button'); del.type='button'; del.textContent='×'; del.title=(L()==='AR'?'مسح':'Clear'); del.style.minWidth='32px'; del.style.height='32px'; del.style.border='1px solid #d9e1ea'; del.style.background='#fff'; del.style.borderRadius='8px'; del.style.marginInlineStart='8px'; del.onclick=()=>{ c.value=''; c.dispatchEvent(new Event('input')); }; td.appendChild(del);} tr.appendChild(td); }); table.appendChild(tr); }); wrap.appendChild(table); host.innerHTML=''; host.appendChild(wrap); }

  function uniq(arr){ const s=new Set(); const out=[]; for(const v of (arr||[])){ const t=String(v||'').trim(); if(!t) continue; const k=t.toLowerCase(); if(s.has(k)) continue; s.add(k); out.push(t); } return out; }
  function gatherLists(wb){ const out={cond:[], freq:[], emp:[]}; for(const name of wb.SheetNames){ try{ const ws=wb.Sheets[name]; const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''}); const head=(rows[0]||[]).map(String); const low=head.map(x=> String(x).toLowerCase()); const idx=(kw)=> low.findIndex(h=> h.includes(kw)); const push=(i,k)=>{ if(i<0) return; for(let r=1;r<rows.length;r++) out[k].push(rows[r][i]); };
      push(idx('condition'),'cond'); (function(){ for(let i=0;i<low.length;i++){ const s=low[i]; if(s.includes('p.m')&&s.includes('freq')) return push(i,'freq'); if(s.includes('pm')&&s.includes('freq')) return push(i,'freq'); } })(); push(idx('maintenance employee name'),'emp'); }catch(_){ } } out.cond=uniq(out.cond.concat(L()==='AR'?COND_FIX_AR:COND_FIX_EN)); out.freq=uniq(out.freq.concat(L()==='AR'?FREQ_FIX_AR:FREQ_FIX_EN)); out.emp =uniq(out.emp.concat(EMP_FIX)); return out; }

  function parseDate(v){ const d=new Date(v); return isFinite(d)? d:null; }
  function normalizeFreq(v){ v=String(v||'').toLowerCase(); if(/daily|يومي/.test(v)) return 'daily'; if(/weekly|أسبوع/.test(v)) return 'weekly'; if(/monthly|شهري|منثلي/.test(v)) return 'monthly'; return ''; }
  function dueToday(freq, ref){ const today=new Date(); today.setHours(0,0,0,0); if(!freq) return false; const refD=parseDate(ref)|| new Date(0); const base=new Date(refD.getFullYear(), refD.getMonth(), refD.getDate()); if(freq==='daily') return true; if(freq==='weekly') return today.getDay()===base.getDay(); if(freq==='monthly') return today.getDate()===base.getDate(); return false; }

  function exportPM(head,data,sheet){ try{ if(!window.XLSX){ alert('XLSX lib missing'); return; } const ws=XLSX.utils.aoa_to_sheet([head, ...data]); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb, ws, sheet||'Sheet1'); XLSX.writeFile(wb, 'PM MAINTENANCE (edited).xlsx'); }catch(_){ alert(L()==='AR'?'تعذّر تصدير XLSX':'Failed to export XLSX'); } }

  async function openAdmin(name){ lastName=name||lastName; qa('.section').forEach(s=> s.classList.remove('active')); const sec=$('adminSection'); if(!sec) return; sec.classList.add('active'); sec.dir=(L()==='AR'?'rtl':'ltr'); const t=T(); sec.innerHTML=`<div class="headerCard"><div class="title">${t.hello} ${lastName||''}</div><div class="thinGreen"></div><p class="hint" id="pmHint">${t.hint}</p><div class="actions-bar"><input id="pmSearch" type="text" placeholder="${t.search}" style="padding:12px;border:2px solid #b9c3d5;border-radius:10px;min-width:260px;font-size:15px"><button id="btnSaveLocal" class="secondary">${t.save}</button><button id="btnExportPM" class="secondary">${t.exportPM}</button><button id="btnBackAdmin" class="ghost">${t.back}</button></div></div><div id="pmTopScroll"><div id="pmTopInner"></div></div><div id="pmTableScroll" style="max-width:100%"><div id="pmTableWrap" class="group" style="padding:8px; min-width:2200px"></div></div><div class="group" style="margin-top:10px" id="dailyBox"><h4>${t.daily} — ${t.shift}</h4><div id="dailyCounts" class="hint" style="margin:0 8px 6px"></div><div class="actions-bar"><button id="btnGenDaily" class="secondary">${t.gen}</button><button id="btnExportDailyPDF" class="primary">${t.dailyPdf}</button><button id="btnShareDaily" class="ghost">${t.share}</button></div><div id="dailyWrap" style="padding:8px"></div></div>`;
    $('btnBackAdmin').onclick=()=>{ qa('.section').forEach(s=> s.classList.remove('active')); $('homeSection')?.classList.add('active'); };

    const {ab}=await fetchPMFile(); const wb=XLSX.read(new Uint8Array(ab),{type:'array'}); const ws=wb.Sheets[wb.SheetNames[0]]; const rows=XLSX.utils.sheet_to_json(ws,{header:1,defval:''}); const head=rows[0]||[]; const low=head.map(x=> String(x).toLowerCase()); let data=rows.slice(1);
    const lists=gatherLists(wb);
    const wrap=$('pmTableWrap'); renderTable(head, low, data, wrap, lists);

    $('btnSaveLocal').onclick=()=>{ try{ localStorage.setItem('pm_edit_snapshot', JSON.stringify({ts:Date.now(), head, rows:data})); alert(L()==='AR'?'تم الحفظ (ON)':'Saved (ON)'); }catch(_){ alert('Save failed'); } };
    $('btnExportPM').onclick=()=> exportPM(head,data,wb.SheetNames[0]);

    const search=$('pmSearch'); if(search){ const doFilter=()=>{ const term=(search.value||'').trim().toUpperCase(); const iCode=low.findIndex(x=> x.includes('code')); const filtered = term? data.filter(r=> String(r[iCode]||'').toUpperCase().includes(term)) : data; renderTable(head,low,filtered,wrap,lists); }; search.oninput=()=> doFilter(); doFilter(); }

    function gen(){ const host=$('dailyWrap'); const counts=$('dailyCounts'); if(host) host.innerHTML=''; if(counts) counts.textContent=''; const iCode=low.findIndex(x=> x.includes('code')); const iName=low.findIndex(x=> x.includes('machine')); const iLoc=low.findIndex(x=> x.includes('location')); const iFreq=(function(){ for(let i=0;i<low.length;i++){ const s=low[i]; if(s.includes('p.m')&&s.includes('freq')) return i; if(s.includes('pm')&&s.includes('freq')) return i; } return -1; })(); const iPMD=low.findIndex(x=> x.includes('p.m date')||x.includes('pm date')); const iLast=low.findIndex(x=> x.includes('last service')); if([iCode,iName,iLoc,iFreq].some(i=> i<0)){ if(counts) counts.textContent=(L()==='AR'?'تعذّر تحديد الأعمدة الأساسية (Code/Name/Location/Frequency).':'Missing key columns (Code/Name/Location/Frequency).'); return false; } const arr=data.filter(r=> String(r[iCode]||'').trim()).filter(r=> dueToday(normalizeFreq(r[iFreq]), r[iPMD]||r[iLast])).map(r=> ({code:r[iCode], name:r[iName], location:r[iLoc]})); const A=[],B=[],C=[]; arr.forEach((x,i)=>{ (i%3===0?A:(i%3===1?B:C)).push(x); }); const t=T(); if(counts) counts.textContent=`${t.total}: ${arr.length} — ${t.am} ${t.count} ${A.length} — ${t.pm} ${t.count} ${B.length} — ${t.night} ${t.count} ${C.length}`; const mk=(title,list)=>{ const box=document.createElement('div'); box.className='group'; const h=document.createElement('h4'); h.textContent=`${title} (${list.length})`; box.appendChild(h); const ul=document.createElement('ul'); ul.style.listStyle='disc'; ul.style.paddingInlineStart='18px'; ul.style.font='13px Segoe UI'; ul.style.lineHeight='1.7'; list.forEach(o=>{ const li=document.createElement('li'); li.textContent=`${o.code} — ${o.name} — ${o.location}`; ul.appendChild(li); }); box.appendChild(ul); return box; }; const grid=document.createElement('div'); grid.style.display='grid'; grid.style.gridTemplateColumns='repeat(auto-fit,minmax(300px,1fr))'; grid.style.gap='12px'; grid.appendChild(mk(T().am,A)); grid.appendChild(mk(T().pm,B)); grid.appendChild(mk(T().night,C)); if(host) host.appendChild(grid); return true; }
    $('btnGenDaily').onclick=()=>{ try{ gen(); }catch(e){ alert('Generate failed: '+(e&&e.message?e.message:e)); } };

    $('btnExportDailyPDF').onclick= async ()=>{ try{ const ok=gen(); if(!ok) return; const html2c=window.html2canvas || (typeof html2canvas!=='undefined'? html2canvas:null); const jsPDFCtor=(window.jspdf && window.jspdf.jsPDF)? window.jspdf.jsPDF : (window.jsPDF? window.jsPDF : null); if(!(html2c && jsPDFCtor)) throw new Error('PDF libs missing'); const pdf=new jsPDFCtor('p','pt','a4'); const t=T(); const stamp=(function(){ const d=new Date(); const daysAR=['الأحد','الإثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت']; const daysEN=['Sun','Mon','Tue','Wed','Thu','Fri','Sat']; const dn=(L()==='AR'?daysAR:daysEN)[d.getDay()]; const y=d.getFullYear(); const m=String(d.getMonth()+1).padStart(2,'0'); const dd=String(d.getDate()).padStart(2,'0'); const hh=String(d.getHours()).padStart(2,'0'); const mi=String(d.getMinutes()).padStart(2,'0'); return `${dn} ${y}-${m}-${dd} ${hh}:${mi}`; })(); const build=async(title)=>{ const root=document.createElement('div'); root.style.width='780px'; root.style.padding='10px 12px'; root.style.position='fixed'; root.style.left='-20000px'; root.style.top='0'; root.style.background='#fff'; root.dir=(L()==='AR'?'rtl':'ltr'); root.innerHTML=`<div class="brand"><img src="./assets/dnata_logo.jpg" style="height:24px;vertical-align:middle" onerror="this.style.display='none'"></div><div class="print-title" style="font:600 16px Segoe UI;margin:2px 0 4px">${t.daily} — ${title}</div><div class="print-line" style="height:3px;background:#1bb34f;margin:4px 0"></div><div style="font:11px Segoe UI; color:#637083;line-height:1.4">${(L()==='AR'?'التاريخ/اليوم/الوقت: ':'Date/Day/Time: ')}${stamp}</div>`; const block=$('dailyWrap')? $('dailyWrap').cloneNode(true): document.createElement('div'); Array.from(block.querySelectorAll('.group')).forEach(g=>{ const h=g.querySelector('h4'); if(!h || h.textContent.indexOf(title)===-1) g.remove(); }); root.appendChild(block); document.body.appendChild(root); const canvas=await html2c(root,{scale:2,useCORS:true,background:'#fff',allowTaint:true}); const pageW=pdf.internal.pageSize.getWidth(); const pageH=pdf.internal.pageSize.getHeight(); const fullW=canvas.width, fullH=canvas.height; const pxPerPt=fullW/pageW; const bottom=28.35; const usableHpt=pageH-bottom; const sliceHpx=Math.floor(usableHpt*pxPerPt); const pg=document.createElement('canvas'); const cx=pg.getContext('2d'); pg.width=fullW; let y=0; let first=true; while(y<fullH){ const h=Math.min(sliceHpx, fullH-y); pg.height=h; cx.clearRect(0,0,fullW,h); cx.drawImage(canvas,0,y,fullW,h,0,0,fullW,h); const img=pg.toDataURL('image/jpeg',0.96); const hPt=h/pxPerPt; if(!first) pdf.addPage(); pdf.addImage(img,'JPEG',0,0,pageW,hPt); first=false; y+=h; } document.body.removeChild(root); };
      await build(T().am); await build(T().pm); await build(T().night); pdf.save('Daily PM List (3 shifts).pdf'); }catch(e){ alert('Export failed: '+(e&&e.message?e.message:e)); } };
  }

  setInterval(()=>{ try{ const ln=L(); if(ln!==renderedLang){ renderedLang=ln; const sec=$('adminSection'); if(sec && sec.classList.contains('active')) openAdmin(lastName); } }catch(_){ } }, 800);
  document.addEventListener('DOMContentLoaded', ()=>{ const b=$('btnAdmin'); if(b && !b._bound){ b.addEventListener('click',(e)=>{ e.preventDefault(); e.stopPropagation(); askPinAndOpen(); }); b._bound=true; } });

  window.askPinAndOpen = askPinAndOpen;
})();
